import type {
  DemandSubmission,
  Notification,
  Registration,
  Review,
  SiteMessage,
  SiteNotice,
  SmsLog,
  Submission,
  User,
} from "./types";

export const DEMO_ACCOUNTS = [
  { role: "user" as const, phone: "13700000001", password: "User@2026", label: "参赛用户" },
  { role: "judge" as const, phone: "13900000001", password: "Judge@2026", label: "评审专家" },
  { role: "admin" as const, phone: "13800000000", password: "Admin@2026", label: "管理员" },
];

export const SEED_USERS: User[] = [
  {
    id: "u_admin",
    phone: "13800000000",
    username: "组委会管理员",
    password: "Admin@2026",
    role: "admin",
    status: "active",
    email: "admin@ai-manufacturing.cn",
    organization: "大赛组委会",
    title: "运营负责人",
    createdAt: "2026-08-01T00:00:00.000Z",
    permissions: { canApply: false, canSubmitWork: false, canReview: false },
  },
  {
    id: "u_judge1",
    phone: "13900000001",
    username: "王教授",
    password: "Judge@2026",
    role: "judge",
    status: "active",
    email: "wang@example.edu.cn",
    organization: "上海交通大学",
    title: "首席专家",
    createdAt: "2026-08-10T00:00:00.000Z",
    permissions: { canApply: false, canSubmitWork: false, canReview: true },
  },
  {
    id: "u_judge2",
    phone: "13900000002",
    username: "李工",
    password: "Judge@2026",
    role: "judge",
    status: "active",
    email: "li@industry.cn",
    organization: "智能制造产业联盟",
    title: "技术委员",
    createdAt: "2026-08-12T00:00:00.000Z",
    permissions: { canApply: false, canSubmitWork: false, canReview: true },
  },
  {
    id: "u_judge3",
    phone: "13900000003",
    username: "赵研究员",
    password: "Judge@2026",
    role: "judge",
    status: "active",
    email: "zhao-judge@example.edu.cn",
    organization: "同济大学",
    title: "评审专家",
    createdAt: "2026-08-13T00:00:00.000Z",
    permissions: { canApply: false, canSubmitWork: false, canReview: true },
  },
  {
    id: "u_judge4",
    phone: "13900000004",
    username: "周总工",
    password: "Judge@2026",
    role: "judge",
    status: "active",
    email: "zhou@industry.cn",
    organization: "上海电气集团",
    title: "总工程师",
    createdAt: "2026-08-14T00:00:00.000Z",
    permissions: { canApply: false, canSubmitWork: false, canReview: true },
  },
  {
    id: "u_judge5",
    phone: "13900000005",
    username: "吴工匠",
    password: "Judge@2026",
    role: "judge",
    status: "active",
    email: "wu@craftsman.cn",
    organization: "上海市机电工会",
    title: "首席技师",
    createdAt: "2026-08-15T00:00:00.000Z",
    permissions: { canApply: false, canSubmitWork: false, canReview: true },
  },
  {
    id: "u_user1",
    phone: "13700000001",
    username: "张智造",
    password: "User@2026",
    role: "user",
    status: "active",
    email: "zhang@example.com",
    organization: "上海电气自动化集团",
    title: "CTO",
    createdAt: "2026-09-01T00:00:00.000Z",
    permissions: { canApply: true, canSubmitWork: true, canReview: false },
  },
  {
    id: "u_user2",
    phone: "13700000002",
    username: "陈小工",
    password: "User@2026",
    role: "user",
    status: "active",
    email: "chen@example.com",
    organization: "上海电气电站集团",
    title: "研究生",
    createdAt: "2026-09-02T00:00:00.000Z",
    permissions: { canApply: true, canSubmitWork: true, canReview: false },
  },
  {
    id: "u_user3",
    phone: "13700000003",
    username: "刘工匠",
    password: "User@2026",
    role: "user",
    status: "disabled",
    email: "liu@example.com",
    organization: "库帕斯有限公司",
    createdAt: "2026-09-03T00:00:00.000Z",
    permissions: { canApply: false, canSubmitWork: false, canReview: false },
  },
  {
    id: "u_user4",
    phone: "13700000004",
    username: "周航",
    password: "User@2026",
    role: "user",
    status: "active",
    email: "zhou@sec-wind.example",
    organization: "上海电气风电集团",
    title: "数字化主管",
    createdAt: "2026-09-04T00:00:00.000Z",
    permissions: { canApply: true, canSubmitWork: true, canReview: false },
  },
  {
    id: "u_user5",
    phone: "13700000005",
    username: "吴澜",
    password: "User@2026",
    role: "user",
    status: "active",
    email: "wu@sec-nuclear.example",
    organization: "上海电气核电集团",
    title: "项目经理",
    createdAt: "2026-09-04T00:00:00.000Z",
    permissions: { canApply: true, canSubmitWork: true, canReview: false },
  },
  {
    id: "u_user6",
    phone: "13700000006",
    username: "郑启明",
    password: "User@2026",
    role: "user",
    status: "active",
    email: "zheng@agibot.example",
    organization: "智元机器人有限公司",
    title: "算法负责人",
    createdAt: "2026-09-05T00:00:00.000Z",
    permissions: { canApply: true, canSubmitWork: true, canReview: false },
  },
  {
    id: "u_user7",
    phone: "13700000007",
    username: "沈柯",
    password: "User@2026",
    role: "user",
    status: "active",
    email: "shen@lingang.example",
    organization: "临港新片区智能制造研究院",
    title: "研究员",
    createdAt: "2026-09-05T00:00:00.000Z",
    permissions: { canApply: true, canSubmitWork: true, canReview: false },
  },
];

export const SEED_REGISTRATIONS: Registration[] = [
  {
    id: "r_1001",
    userId: "u_user1",
    createdAt: "2026-09-05T02:30:00.000Z",
    status: "registered",
    registrationDate: "2026-09-05",
    projectName: "视界·少样本缺陷检测平台",
    organizationName: "上海电气自动化集团",
    leaderName: "张智造",
    leaderTitle: "CTO",
    organizationCity: "上海市",
    organizationDistrict: "浦东新区",
    organizationDetail: "张江路 88 号",
    organizationAddress: "上海市浦东新区张江路 88 号",
    direction: "AI+生产制造",
    projectContent:
      "意义与目标：降低 3C/汽车零部件产线质检对海量标注样本的依赖。主要内容：基于视觉基础模型微调与异常检测蒸馏，支持 20 张样本快速建模。预期成果：检出率 ≥99.5%，误检率 ≤0.3%，部署周期从 2 周缩短到 2 天。推广价值：可复制到多品类外观检测产线。",
    members: [
      { name: "张智造", age: "36", gender: "男", phone: "13700000001", email: "zhang@example.com" },
      { name: "赵研", age: "29", gender: "女", phone: "13700000011", email: "zhao@example.com" },
    ],
    contactName: "张智造",
    contactPhone: "13700000001",
    stampedFormName: "视界少样本缺陷检测平台_盖章报名表.pdf",
    workPackageName: "AI生产制造_视界少样本缺陷检测平台_张智造.zip",
    registrationAudit: "passed",
    materialsAudit: "passed",
    reviewScore: 89,
    enteredFinals: true,
    awardLevel: "一等奖",
  },
  {
    id: "r_1002",
    userId: "u_user2",
    createdAt: "2026-09-06T09:12:00.000Z",
    status: "need_revision",
    registrationDate: "2026-09-06",
    projectName: "轴承健康数字孪生",
    organizationName: "上海电气电站集团",
    leaderName: "陈小工",
    leaderTitle: "项目负责人",
    organizationCity: "上海市",
    organizationDistrict: "徐汇区",
    organizationDetail: "梅陇路 130 号",
    organizationAddress: "上海市徐汇区梅陇路 130 号",
    direction: "AI+运行维护",
    projectContent:
      "意义与目标：面向旋转设备实现可冷启动的预测性维护。主要内容：振动+温度多源时序 Transformer，剩余寿命预测。预期成果：寿命预测误差 < 8%，支持边缘部署。推广价值：可用于风电齿轮箱、数控机床主轴等场景。",
    members: [
      { name: "陈小工", age: "27", gender: "男", phone: "13700000002", email: "chen@example.com" },
    ],
    contactName: "陈小工",
    contactPhone: "13700000002",
    stampedFormName: "轴承健康数字孪生_盖章报名表.pdf",
    workPackageName: "AI运行维护_轴承健康数字孪生_陈小工.zip",
    registrationAudit: "passed",
    materialsAudit: "need_revision",
    materialsAuditNote: "压缩包内缺少项目视频与代码目录，请按命名规范重新打包后上传。",
    reviewScore: 72,
    enteredFinals: false,
  },
  {
    id: "r_1003",
    userId: "u_user3",
    createdAt: "2026-09-07T14:40:00.000Z",
    status: "registered",
    registrationDate: "2026-09-07",
    projectName: "工艺知识智能体 CraftGPT",
    organizationName: "库帕斯有限公司",
    leaderName: "刘工匠",
    leaderTitle: "负责人",
    organizationCity: "深圳市",
    organizationDistrict: "南山区",
    organizationDetail: "科技园",
    organizationAddress: "深圳市南山区科技园",
    direction: "AI+研发设计",
    projectContent:
      "意义与目标：沉淀注塑工艺知识，降低工艺师上手门槛。主要内容：RAG + 工艺知识图谱 + 工具调用。预期成果：覆盖参数推荐与异常归因。推广价值：可扩展至多品类工艺知识库。",
    members: [],
    contactName: "刘工匠",
    contactPhone: "13700000003",
    registrationAudit: "pending",
    materialsAudit: "pending",
  },
  {
    id: "r_1004",
    userId: "u_user4",
    createdAt: "2026-09-08T03:10:00.000Z",
    status: "work_submitted",
    registrationDate: "2026-09-08",
    projectName: "风机叶片视觉巡检",
    organizationName: "上海电气风电集团",
    leaderName: "周航",
    leaderTitle: "数字化主管",
    organizationCity: "上海市",
    organizationDistrict: "浦东新区",
    organizationDetail: "临港大道 2000 号",
    organizationAddress: "上海市浦东新区临港大道 2000 号",
    direction: "AI+运行维护",
    projectContent:
      "意义与目标：降低海上风机叶片人工巡检风险。主要内容：无人机采集 + 损伤识别。预期成果：单台巡检缩短至 40 分钟。推广价值：可复制到陆上风电场。",
    members: [],
    contactName: "周航",
    contactPhone: "13700000004",
    stampedFormName: "风机叶片视觉巡检_盖章报名表.pdf",
    workPackageName: "AI运行维护_风机叶片视觉巡检_周航.zip",
    registrationAudit: "passed",
    materialsAudit: "pending",
  },
  {
    id: "r_1005",
    userId: "u_user5",
    createdAt: "2026-09-08T08:40:00.000Z",
    status: "materials_review",
    registrationDate: "2026-09-08",
    projectName: "核电阀门智能装配助手",
    organizationName: "上海电气核电集团",
    leaderName: "吴澜",
    leaderTitle: "项目经理",
    organizationCity: "上海市",
    organizationDistrict: "闵行区",
    organizationDetail: "剑川路 869 号",
    organizationAddress: "上海市闵行区剑川路 869 号",
    direction: "AI+生产制造",
    projectContent:
      "意义与目标：提升核电阀门装配一次合格率。主要内容：三维指引与力矩闭环。预期成果：装配返工下降 30%。推广价值：可用于其他核安全级部件。",
    members: [],
    contactName: "吴澜",
    contactPhone: "13700000005",
    stampedFormName: "核电阀门智能装配助手_盖章报名表.pdf",
    workPackageName: "AI生产制造_核电阀门智能装配助手_吴澜.zip",
    registrationAudit: "passed",
    materialsAudit: "passed",
    reviewScore: 80,
  },
  {
    id: "r_1006",
    userId: "u_user6",
    createdAt: "2026-09-09T02:15:00.000Z",
    status: "need_revision",
    registrationDate: "2026-09-09",
    projectName: "产线协作机器人排程",
    organizationName: "智元机器人有限公司",
    leaderName: "郑启明",
    leaderTitle: "算法负责人",
    organizationCity: "上海市",
    organizationDistrict: "浦东新区",
    organizationDetail: "张江科学城",
    organizationAddress: "上海市浦东新区张江科学城",
    direction: "AI+经营管理",
    projectContent:
      "意义与目标：多机协同排程降低待料。主要内容：强化学习调度。预期成果：产线 OEE 提升 8%。推广价值：可迁移至 3C 装配岛。",
    members: [],
    contactName: "郑启明",
    contactPhone: "13700000006",
    registrationAudit: "need_revision",
    registrationAuditNote: "单位地址请补充到门牌号，项目内容请补充可量化指标的统计口径。",
    materialsAudit: "pending",
  },
  {
    id: "r_1007",
    userId: "u_user7",
    createdAt: "2026-09-09T11:00:00.000Z",
    status: "materials_review",
    registrationDate: "2026-09-09",
    projectName: "临港工厂能碳优化大脑",
    organizationName: "临港新片区智能制造研究院",
    leaderName: "沈柯",
    leaderTitle: "研究员",
    organizationCity: "上海市",
    organizationDistrict: "浦东新区",
    organizationDetail: "飞渡路 1 号",
    organizationAddress: "上海市浦东新区飞渡路 1 号",
    direction: "AI原生智能工厂建设方案",
    projectContent:
      "意义与目标：以能碳数据驱动工厂运行。主要内容：负荷预测与工艺协同。预期成果：综合能耗下降 6%。推广价值：可服务临港园区多工厂。",
    members: [],
    contactName: "沈柯",
    contactPhone: "13700000007",
    stampedFormName: "临港工厂能碳优化大脑_盖章报名表.pdf",
    workPackageName: "AI原生智能工厂建设方案_临港工厂能碳优化大脑_沈柯.zip",
    registrationAudit: "passed",
    materialsAudit: "passed",
    reviewScore: 74,
  },
];

export const SEED_SUBMISSIONS: Submission[] = [
  {
    id: "s_2001",
    registrationId: "r_1001",
    title: "视界·少样本缺陷检测平台",
    team: "上海电气自动化集团",
    track: "AI+生产制造",
    summary:
      "基于视觉大模型的少样本工业缺陷检测平台，支持 20 张样本快速建模，已在 3C 与汽车零部件产线部署。",
    fileName: "AI生产制造_视界少样本缺陷检测平台_张智造.zip",
    fileUrl: "/samples/vision-defect-detection.zip",
    fileSize: "1.2 KB",
    submittedAt: "2026-09-08T06:00:00.000Z",
    assignedJudgeIds: ["u_judge1", "u_judge2"],
  },
  {
    id: "s_2002",
    registrationId: "r_1002",
    title: "轴承健康数字孪生",
    team: "上海电气电站集团",
    track: "AI+运行维护",
    summary: "面向旋转设备的多模态预测性维护系统，支持冷启动与边缘部署。",
    fileName: "AI运行维护_轴承健康数字孪生_陈小工.zip",
    fileUrl: "/samples/bearing-twin.zip",
    fileSize: "0.8 KB",
    submittedAt: "2026-09-09T03:20:00.000Z",
    assignedJudgeIds: [],
  },
  {
    id: "s_2004",
    registrationId: "r_1004",
    title: "风机叶片视觉巡检",
    team: "上海电气风电集团",
    track: "AI+运行维护",
    summary: "面向海上风机叶片的无人机巡检与损伤识别方案。",
    fileName: "AI运行维护_风机叶片视觉巡检_周航.zip",
    fileUrl: "/samples/bearing-twin.zip",
    fileSize: "0.9 KB",
    submittedAt: "2026-09-10T02:00:00.000Z",
    assignedJudgeIds: [],
  },
  {
    id: "s_2005",
    registrationId: "r_1005",
    title: "核电阀门智能装配助手",
    team: "上海电气核电集团",
    track: "AI+生产制造",
    summary: "核电阀门装配三维指引与力矩闭环助手。",
    fileName: "AI生产制造_核电阀门智能装配助手_吴澜.zip",
    fileUrl: "/samples/vision-defect-detection.zip",
    fileSize: "1.0 KB",
    submittedAt: "2026-09-10T04:20:00.000Z",
    assignedJudgeIds: ["u_judge1", "u_judge4"],
  },
  {
    id: "s_2007",
    registrationId: "r_1007",
    title: "临港工厂能碳优化大脑",
    team: "临港新片区智能制造研究院",
    track: "AI原生智能工厂建设方案",
    summary: "以能碳数据驱动的工厂运行优化方案。",
    fileName: "AI原生智能工厂建设方案_临港工厂能碳优化大脑_沈柯.zip",
    fileUrl: "/samples/craftgpt.zip",
    fileSize: "0.7 KB",
    submittedAt: "2026-09-10T06:40:00.000Z",
    assignedJudgeIds: ["u_judge3"],
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "rv_1",
    submissionId: "s_2001",
    judgeId: "u_judge2",
    scores: { fit: 18, innovation: 18, technology: 17, completeness: 16, business: 18 },
    total: 87,
    comment: "少样本建模路径清晰，产线指标扎实，建议补充跨工厂泛化实验与误检样本回流机制。",
    status: "submitted",
    submittedAt: "2026-09-09T08:00:00.000Z",
  },
  {
    id: "rv_2",
    submissionId: "s_2001",
    judgeId: "u_judge1",
    scores: { fit: 19, innovation: 18, technology: 18, completeness: 18, business: 18 },
    total: 91,
    comment: "场景真实、部署周期有说服力，工程完成度高。建议在材料中补充多工厂迁移的约束条件与失败案例。",
    status: "submitted",
    submittedAt: "2026-09-09T10:20:00.000Z",
  },
  {
    id: "rv_3",
    submissionId: "s_2005",
    judgeId: "u_judge1",
    scores: { fit: 16, innovation: 15, technology: 17, completeness: 17, business: 17 },
    total: 82,
    comment: "核电装配指引与力矩闭环结合得好，合规意识清楚。演示视频偏短，建议补充现场一次装配对照数据。",
    status: "submitted",
    submittedAt: "2026-09-11T02:10:00.000Z",
  },
  {
    id: "rv_4",
    submissionId: "s_2005",
    judgeId: "u_judge4",
    scores: { fit: 15, innovation: 14, technology: 16, completeness: 16, business: 17 },
    total: 78,
    comment: "面向核安全级部件的落地路径可行，但创新性一般，文档对异常工况的覆盖还不够完整。",
    status: "submitted",
    submittedAt: "2026-09-11T03:40:00.000Z",
  },
  {
    id: "rv_5",
    submissionId: "s_2007",
    judgeId: "u_judge3",
    scores: { fit: 14, innovation: 13, technology: 16, completeness: 16, business: 15 },
    total: 74,
    comment: "能碳协同方向符合智能工厂命题，指标口径需写清边界，建议补充园区多工厂的可复制方案。",
    status: "submitted",
    submittedAt: "2026-09-11T06:15:00.000Z",
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: "n_1",
    userId: "u_user1",
    title: "报名成功",
    body: "您的项目「视界·少样本缺陷检测平台」已完成报名。请下载报名表。加盖企业公章后的报名表，请在提交作品阶段一并上传；届时再将 PPT、文档、视频、代码等打成压缩包提交，命名为「赛道方向_项目名称_负责人」。",
    createdAt: "2026-09-06T01:00:00.000Z",
    read: false,
    type: "contest",
  },
  {
    id: "n_2",
    userId: "u_user1",
    title: "作品已分配评审",
    body: "您的作品已进入初赛评审阶段，评审结果将在 2 周内反馈。",
    createdAt: "2026-09-08T10:00:00.000Z",
    read: true,
    type: "review",
  },
  {
    id: "n_3",
    userId: "u_judge1",
    title: "新的评审任务",
    body: "您有 2 件新作品待评审，请在截止日期前完成评分。",
    createdAt: "2026-09-08T07:00:00.000Z",
    read: false,
    type: "review",
  },
  {
    id: "n_4",
    userId: "u_user2",
    title: "参赛材料需修改",
    body: "您的项目「轴承健康数字孪生」材料审核未通过：压缩包内缺少项目视频与代码目录，请按命名规范重新打包后上传。",
    createdAt: "2026-09-10T08:00:00.000Z",
    read: false,
    type: "review",
  },
];

export const SEED_MESSAGES: SiteMessage[] = [
  {
    id: "m_1",
    userId: "u_user1",
    username: "张智造",
    account: "13700000001",
    contact: "13700000001",
    content: "盖章报名表上传后，个人中心「提交作品」仍显示未完成，请协助核对进度。",
    attachmentName: "个人中心进度截图.png",
    attachmentUrl: "/crystal-gear-mini.png",
    attachments: [{ name: "个人中心进度截图.png", url: "/crystal-gear-mini.png" }],
    status: "processing",
    createdAt: "2026-09-09T04:12:00.000Z",
  },
  {
    id: "m_2",
    userId: null,
    username: "未登录访客",
    account: "",
    contact: "13911112222",
    content: "请问报名截止后单位盖章来不及，是否可以延期提交盖章件？",
    attachmentName: "",
    status: "processed",
    createdAt: "2026-09-08T11:40:00.000Z",
  },
  {
    id: "m_3",
    userId: "u_user2",
    username: "陈小工",
    account: "13700000002",
    contact: "chen@example.com",
    content: "压缩包已按意见补充视频，上传时页面报错，附件为报错截图。",
    attachmentName: "上传失败截图.png",
    attachmentUrl: "/hero-nebula.png",
    attachments: [{ name: "上传失败截图.png", url: "/hero-nebula.png" }],
    status: "processing",
    createdAt: "2026-09-10T09:20:00.000Z",
  },
];

export const SEED_NOTICES: SiteNotice[] = [
  {
    id: "nt_1",
    title: "关于提交作品压缩包命名的说明",
    body: "请将 PPT、文档、视频、代码等打包为 zip/rar/7z，命名为「赛道方向_项目名称_负责人」。未按规范命名可能影响审核。",
    target: "user",
    publishedAt: "2026-09-04T02:00:00.000Z",
    updatedAt: "2026-09-04T02:00:00.000Z",
    authorId: "u_admin",
  },
];

export const SEED_SMS: SmsLog[] = [
  {
    id: "sms_1",
    userId: "u_user2",
    phone: "13700000002",
    title: "参赛材料需修改",
    body: "【AI原生工厂大赛】您的项目「轴承健康数字孪生」材料审核未通过，请登录个人中心查看修改意见。",
    createdAt: "2026-09-10T08:00:00.000Z",
  },
];

export const SEED_DEMANDS: DemandSubmission[] = [
  {
    id: "d_1",
    userId: "u_user1",
    createdAt: "2026-09-08T03:20:00.000Z",
    organizationName: "上海电气自动化集团",
    organizationCity: "上海市",
    organizationDistrict: "闵行区",
    organizationDetail: "剑川路 1320 号",
    organizationAddress: "上海市闵行区剑川路 1320 号",
    contactName: "张智造",
    contactTitle: "CTO",
    contactPhone: "13700000001",
    contactEmail: "zhang@example.com",
    title: "焊接环缝在线视觉检测需求",
    direction: "AI+生产制造",
    otherDirection: "",
    content:
      "压力容器环缝焊接目前依赖人工目检，漏检与过检并存。希望建设可部署在现有产线旁的视觉检测能力，识别气孔、咬边、未熔合等典型缺陷，并把结果回传到工艺记录。",
    expected: "漏检率低于 3%；单条焊缝判定时延不超过 2 秒；支持导出缺陷图片与批次统计报表。",
    status: "pending",
  },
  {
    id: "d_2",
    userId: "u_user2",
    createdAt: "2026-09-07T09:10:00.000Z",
    organizationName: "上海电气电站集团",
    organizationCity: "上海市",
    organizationDistrict: "闵行区",
    organizationDetail: "江川路 333 号",
    organizationAddress: "上海市闵行区江川路 333 号",
    contactName: "陈小工",
    contactTitle: "研究生",
    contactPhone: "13700000002",
    contactEmail: "chen@example.com",
    title: "大型机组预测性维护场景",
    direction: "AI+运行维护",
    otherDirection: "",
    content:
      "希望针对大型压缩机与辅机建立预测性维护模型，融合振动、温度与检修工单，提前识别轴承与密封类故障，减少非计划停机。",
    expected: "典型故障提前 72 小时预警；误报率可控；给出可执行的检修建议清单。",
    status: "accepted",
    auditNote: "场景完整，拟纳入下届揭榜选题库。",
  },
];
